import { type NextPage } from 'next';
import Head from 'next/head';
import { Button } from 'ui';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Button
          onClick={() => {
            console.log('test');
          }}
        >
          test
        </Button>
      </main>
    </>
  );
};

export default Home;
