name: Deploy API to Heroku
on:
  push:
    branches:
      - main
    paths:
      - 'apps/chum-api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Build Api
        run: npm run build:api --if-present
        env:
          DISABLE_ERD: ${{secrets.DISABLE_ERD}}

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          branch: 'main'
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'chum-api'
          heroku_email: 'hoanghai129612@gmail.com'
          appdir: 'apps/chum-api'
