name: Deploy
on:
  push:
    branches:
      - main
  path:
    - 'apps/chum-api/**'

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.12.12
          with:
            branch: 'main'
            path: 'apps/chum-api'
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: 'chum-api'
            heroku_email: 'hoanghai129612@gmail.com'
